name: EntityAI
main: EntityAI\Main
version: 0.0.1
api: 3.3.2
load: POSTWORLD
author: hartleyterw
description: An advanced Entity AI module.

commands:
 npc:
  description: "Spawn an NPC"
  usage: "/npc"
  permission: entityai.command

permissions:
 entityai:
  default: op
  description: "Allows all functionality"
  children:
   entityai.command:
    default: op
    description: "Allows the usage of all commands"